# Generated by Django 3.2.7 on 2021-09-21 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('drinks_num', models.CharField(max_length=100)),
            ],
        ),
    ]
